import { ComplianceRequirement } from '../types';

export const DS44_RULESET_VERSION = 'DS44-CHILE-2025-v1';

export const DEFAULT_COMPLIANCE_REQUIREMENTS: ComplianceRequirement[] = [
  {
    id: 'req-01',
    code: 'DS44-ART-04',
    title: 'Política de Seguridad y Salud en el Trabajo',
    description: 'La empresa debe contar con una Política de SST formalizada, firmada por la alta gerencia, fechada y debidamente comunicada a todos los trabajadores.',
    regulation: 'Decreto Supremo N.º 44',
    articleReference: 'Artículo 4',
    category: 'Información y Participación',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'Documento oficial de Política de SST firmado por Gerencia General y comprobante de difusión a trabajadores.',
    frequencyMonths: 12,
    weight: 6,
    criticality: 'Media',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-02',
    code: 'DS44-ART-05',
    title: 'Matriz de Identificación de Peligros y Evaluación de Riesgos (MIPER)',
    description: 'Confección y actualización periódica de la MIPER para todos los centros de trabajo, procesos, actividades y puestos de trabajo.',
    regulation: 'Decreto Supremo N.º 44',
    articleReference: 'Artículo 5',
    category: 'MIPER',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'MIPER vigente aprobada por Prevencionista y Gerencia, con riesgos evaluados y medidas de control jerarquizadas.',
    frequencyMonths: 12,
    weight: 15,
    criticality: 'Crítica',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-03',
    code: 'DS44-ART-06',
    title: 'Programa de Trabajo Preventivo Anual',
    description: 'Establecimiento y ejecución de un Programa Preventivo Anual con cronograma de actividades, responsables, plazos e indicadores de cumplimiento.',
    regulation: 'Decreto Supremo N.º 44',
    articleReference: 'Artículo 6',
    category: 'Programa Preventivo',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'Programa Anual formalizado con seguimiento mensual de acciones preventivas/correctivas ejecutadas y verificadas.',
    frequencyMonths: 12,
    weight: 15,
    criticality: 'Crítica',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-04',
    code: 'DS44-ART-07',
    title: 'Obligación de Informar los Riesgos Laborales (ODI / Inducción)',
    description: 'Informar oportunamente a todos los trabajadores sobre los riesgos inherentes a sus labores, medidas preventivas y métodos de trabajo correctos.',
    regulation: 'Decreto Supremo N.º 44 / DS 40',
    articleReference: 'Artículo 7',
    category: 'Capacitación',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'Registros individuales firmados de Derecho a Saber (ODI) por cada trabajador al ingreso y ante cambios de puesto.',
    frequencyMonths: 12,
    weight: 10,
    criticality: 'Crítica',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-05',
    code: 'DS44-ART-08',
    title: 'Plan de Capacitación y Entrenamiento Continuo',
    description: 'Ejecución de capacitaciones en prevención de riesgos, uso correcto de EPP, manejo de extintores y procedimientos seguros.',
    regulation: 'Decreto Supremo N.º 44',
    articleReference: 'Artículo 8',
    category: 'Capacitación',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'Listas de asistencia con RUT y firma, certificados de aprobación emitidos por OAL (Mutual) o relator competente.',
    frequencyMonths: 6,
    weight: 8,
    criticality: 'Alta',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-06',
    code: 'DS44-ART-09',
    title: 'Programa de Inspecciones y Observaciones de Seguridad',
    description: 'Realización periódica de inspecciones planeadas a instalaciones, herramientas, maquinarias y áreas de trabajo.',
    regulation: 'Decreto Supremo N.º 44',
    articleReference: 'Artículo 9',
    category: 'Inspecciones',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'Informes de inspección fechados, listas de chequeo aplicadas y registro de hallazgos con medidas correctivas asignadas.',
    frequencyMonths: 3,
    weight: 8,
    criticality: 'Alta',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-07',
    code: 'DS44-ART-10',
    title: 'Investigación y Registro de Incidentes y Accidentes',
    description: 'Investigación técnica inmediata de todos los accidentes del trabajo y enfermedades profesionales para determinar causas raíces e implementar acciones.',
    regulation: 'Decreto Supremo N.º 44 / Ley 16.744',
    articleReference: 'Artículo 10',
    category: 'Investigación de Accidentes',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'Informes de investigación técnica con metodología de árbol de causas, DIAT ingresada en OAL y medidas de control en MIPER.',
    frequencyMonths: 1,
    weight: 8,
    criticality: 'Alta',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-08',
    code: 'DS44-ART-11',
    title: 'Plan de Emergencia y Evacuación',
    description: 'Disponer de un plan de emergencia actualizado por centro de trabajo, señalética de vías de evacuación y realización de simulacros anuales.',
    regulation: 'Decreto Supremo N.º 44 / DS 594',
    articleReference: 'Artículo 11',
    category: 'Emergencias',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'Plan de emergencia aprobado por bomberos/mutualidad, planos de evacuación y acta de realización de simulacro anual.',
    frequencyMonths: 12,
    weight: 7,
    criticality: 'Alta',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-09',
    code: 'DS44-ART-12',
    title: 'Comité Paritario de Higiene y Seguridad (CPHS)',
    description: 'Constitución y funcionamiento de Comité Paritario en centros de trabajo con más de 25 trabajadores.',
    regulation: 'Decreto Supremo N.º 54 / DS 44',
    articleReference: 'Artículo 12',
    category: 'Comité Paritario',
    applicabilityRule: 'WORKER_COUNT > 25',
    requiredEvidenceDescription: 'Acta de constitución de CPHS depositada en Inspección del Trabajo y actas de reuniones mensuales firmadas.',
    frequencyMonths: 1,
    weight: 8,
    criticality: 'Alta',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-10',
    code: 'DS44-ART-13',
    title: 'Reglamento Interno de Orden, Higiene y Seguridad (RIOHS)',
    description: 'Contar con RIOHS actualizado conforme a normativas vigentes, depositado ante la DT y Seremi de Salud, y entregado a cada trabajador.',
    regulation: 'Código del Trabajo / DS 44',
    articleReference: 'Artículo 13',
    category: 'Documentación y RIOHS',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'Copia digital del RIOHS con timbres de depósito DT/Seremi y comprobantes de recepción firmados por trabajadores.',
    frequencyMonths: 24,
    weight: 8,
    criticality: 'Crítica',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-11',
    code: 'DS44-ART-14',
    title: 'Dotación, Certificación y Control de EPP',
    description: 'Entrega gratuita de Equipos de Protección Personal certificados por organismo acreditado y control de reposición periódica.',
    regulation: 'DS 594 / DS 44',
    articleReference: 'Artículo 14',
    category: 'Salud Ocupacional y EPP',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'Comprobantes de entrega y recambio de EPP firmados por los trabajadores y certificados de calidad de los elementos.',
    frequencyMonths: 6,
    weight: 7,
    criticality: 'Alta',
    effectiveFrom: '2025-01-01',
    active: true,
  },
  {
    id: 'req-12',
    code: 'DS44-ART-15',
    title: 'Vigilancia de Salud y Exámenes Ocupacionales',
    description: 'Incorporación a programas de vigilancia epidemiológica de la Mutualidad para trabajadores expuestos a riesgos específicos (Ruido, Sílice, Manejo Manual, Conducción).',
    regulation: 'Protocolos MINSAL / DS 44',
    articleReference: 'Artículo 15',
    category: 'Salud Ocupacional y EPP',
    applicabilityRule: 'ALWAYS',
    requiredEvidenceDescription: 'Nómina de trabajadores expuestos en mutualidad y certificados de aptitud ocupacional vigentes.',
    frequencyMonths: 12,
    weight: 8,
    criticality: 'Alta',
    effectiveFrom: '2025-01-01',
    active: true,
  }
];
